services:
  db:
    image: mysql:8.0
    restart: always
    env_file:
      - ".env"
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"

  backend:
    build: ./backend
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - ".env"
  frontend:
    build: ./frontend
    volumes:
      - ./frontend:/app
    ports:
      - "4200:4200"
    depends_on:
      - backend

volumes:
  db_data:
