"""Add initial tables

Revision ID: a19b231f51eb
Revises: 
Create Date: 2025-06-03 09:01:25.937271

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'a19b231f51eb'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    #op.drop_table('teams_in_game')
    #op.drop_index(op.f('ix_teams_activity_id'), table_name='teams')
    #op.drop_index(op.f('ix_teams_team_id'), table_name='teams')
    #op.drop_table('teams')
    #op.drop_index(op.f('ix_fields_id'), table_name='fields')
    #op.drop_index(op.f('ix_fields_name'), table_name='fields')
    #op.drop_table('fields')
    #op.drop_index(op.f('ix_activities_id'), table_name='activities')
    #op.drop_index(op.f('ix_activities_name'), table_name='activities')
    #op.drop_table('activities')
    #op.drop_index(op.f('ix_sports_games_field_id'), table_name='sports_games')
    #op.drop_index(op.f('ix_sports_games_game_id'), table_name='sports_games')
    #op.drop_table('sports_games')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sports_games',
    sa.Column('game_id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('game_name', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('field_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('start_date', mysql.DATETIME(), nullable=False),
    sa.Column('end_date', mysql.DATETIME(), nullable=False),
    sa.Column('booking_type', mysql.ENUM('NORMAL', 'TURNAMENT'), nullable=False),
    sa.Column('weight_tournament', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('is_tournament_verified', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['field_id'], ['fields.id'], name='sports_games_ibfk_1'),
    sa.PrimaryKeyConstraint('game_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_sports_games_game_id'), 'sports_games', ['game_id'], unique=False)
    op.create_index(op.f('ix_sports_games_field_id'), 'sports_games', ['field_id'], unique=False)
    op.create_table('activities',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_activities_name'), 'activities', ['name'], unique=True)
    op.create_index(op.f('ix_activities_id'), 'activities', ['id'], unique=False)
    op.create_table('fields',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_fields_name'), 'fields', ['name'], unique=True)
    op.create_index(op.f('ix_fields_id'), 'fields', ['id'], unique=False)
    op.create_table('teams',
    sa.Column('team_id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('team_name', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('activity_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('amount_players', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('amount_points', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('is_verified', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['activity_id'], ['activities.id'], name='teams_ibfk_1'),
    sa.PrimaryKeyConstraint('team_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_teams_team_id'), 'teams', ['team_id'], unique=False)
    op.create_index(op.f('ix_teams_activity_id'), 'teams', ['activity_id'], unique=False)
    op.create_table('teams_in_game',
    sa.Column('tournament_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('team_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('placed', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('is_join_tournament_verified', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['team_id'], ['teams.team_id'], name=op.f('teams_in_game_ibfk_2')),
    sa.ForeignKeyConstraint(['tournament_id'], ['sports_games.game_id'], name=op.f('teams_in_game_ibfk_1')),
    sa.PrimaryKeyConstraint('tournament_id', 'team_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
